# Generated by Django 3.2.7 on 2021-10-07 05:54

import Gallery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontpage', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
                ('image', models.ImageField(upload_to=Gallery.models.image_dir_path)),
                ('description', models.TextField(max_length=2000)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.category')),
            ],
        ),
    ]
