# Generated by Django 3.2.7 on 2021-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20211007_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
